language: cpp
sudo: enabled

install:
  - sudo apt-get install lcov

before_script:
  - cd test && mkdir build && cd build

script:
  - cmake ..
  - make

after_success:
  - lcov --directory . --zerocounters
  - bin/testArduinoCloudThing
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'test/*' '/usr/*' 'lib/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info
  - cd ..
  - rm -rf build

